Add test first
for now:
expected Frontkick::Timeout, got #<NameError: undefined local variable or method `command' for Frontkick::Command:Class> with backtrace:
./lib/frontkick/command.rb:112:in `rescue in exec'
./lib/frontkick/command.rb:125:in `exec'
./spec/frontkick/command_spec.rb:6:in `block (4 levels) in <top (required)>'
./spec/frontkick/command_spec.rb:7:in `block (5 levels) in <top (required)>'
./spec/frontkick/command_spec.rb:7:in `block (4 levels) in <top (required)>'